a testing ground for D4M stuff ; I'm using this to test commands I don't understand super super well

also works as some janky demo, i guess

In [1]:
using D4M

┌ Info: Recompiling stale cache file /home/nathan/.julia/compiled/v1.0/D4M/JhFK0.ji for D4M [ca196bdc-a701-11e8-3d50-3b5cc8577617]
└ @ Base loading.jl:1190


Database capabilities loaded!
D4M loaded!


In [2]:
D4Mver()

version 0.1.6


In [25]:
r = [1,2,3]
c = [1,2,1]
v=[11,22,33]
A = Assoc(r,c,v)

r = "a,b,a,ab,"
c = "a,b,c,d,"
v="a-a,b-b,a-c,ab-d,"
As = Assoc(r,c,v)

r = "a,b,a,ab,"
c = "a,b,c,d,"
v=[2,3,4,5]
As2 = Assoc(r,c,v)

Assoc(Union{AbstractString, Number}["a", "ab", "b"], Union{AbstractString, Number}["a", "b", "c", "d"], Union{AbstractString, Number}[1.0], 
  [1, 1]  =  2
  [3, 2]  =  3
  [1, 3]  =  4
  [2, 4]  =  5)

In [1]:
function StrUnique(inputString::AbstractString, csv= false)
    #TODO backwardMapping from unique string to index is not implemented, because there doesn't seem to be a application for such an array
    #Note: The unique output is sorted.
    separator = inputString[end]
    if(csv == true)
        separator = ','
    end
    strA = split(inputString,separator)
    if inputString[end] == separator
        strA = strA[1:end-1]
    end

    uniqueSeq = unique(strA)
    sort!(uniqueSeq)
    if uniqueSeq[1] == "" #Handle Empty Case
        uniqueSeq = uniqueSeq[2:end]
    end

    forwardMapping =[ searchsortedfirst(uniqueSeq,x) for x in strA]

    backwardMapping = zeros(1,length(forwardMapping))

    return uniqueSeq,backwardMapping,forwardMapping
end


StrUnique (generic function with 2 methods)

In [12]:
StrUnique("a,c,e,b,d,")

(SubString{String}["a", "b", "c", "d", "e"], [0.0 0.0 … 0.0 0.0], [1, 3, 5, 2, 4])

In [11]:
i = "a,c,e,b,d,"

row = unique(i)
sort!(row)

# Find index of row keys from triples in row (int indices for sparse matrix)
i = convert(AbstractArray{Int64},[searchsortedfirst(row,x) for x in i])

10-element Array{Int64,1}:
 2
 1
 4
 1
 6
 1
 3
 1
 5
 1

In [10]:
row

4-element Array{Int64,1}:
 1
 2
 3
 5

In [15]:
function getcol(A::Assoc)
    if isempty(A)
        return Union{AbstractString, Number}[]
    else
        if isa(A.col[1], AbstractString) || ~(size(A.A,2) == A.col[end])
            return copy(A.col)
        end
        return 1:size(A.A,2)
    end
end

getcol (generic function with 1 method)

In [19]:
getcol(A)

1:2

In [18]:
A.col

2-element Array{Union{AbstractString, Number},1}:
 1
 2

In [20]:
A[StartsWith("1,"), :]

MethodError: MethodError: no method matching StartsWithHelper(::UnitRange{Int64}, ::StartsWith)
Closest candidates are:
  StartsWithHelper(!Matched::Array{Union{AbstractString, Number},N} where N, ::StartsWith) at /home/nathan/Documents/UROP/D4M.jl/src/Assoc/getindex.jl:106

In [21]:
function StartsWithHelper(Ar::Array{Union{AbstractString,Number}},S::StartsWith)
    str_list = []
    if S.inputString[end] == ','
        str_list,tmp = StrUnique(S.inputString)
    else
        str_list = [S.inputString]
    end
    result_indice = Array{Int64,1}()
    for str in str_list
        str_result_first = searchsortedfirst(Ar,str)
        str_result_last = searchsortedlast(Ar,str*string(Char(255)))
        if str_result_first <= str_result_last
            [push!(result_indice,x) for x in str_result_first:str_result_last]
        end
    end
    return result_indice
end

StartsWithHelper (generic function with 1 method)

In [28]:
StartsWithHelper(getrow(As), StartsWith("a"))

2-element Array{Int64,1}:
 1
 2

In [29]:
getrow(As)

3-element Array{Union{AbstractString, Number},1}:
 "a" 
 "ab"
 "b" 

In [11]:
printFull(CatKeyMul(As, As))

3×4 Array{Union{AbstractString, Number},2}:
 ""   "a"   "b"   "c" 
 "a"  "a;"  ""    "a;"
 "b"  ""    "b;"  ""  

In [8]:
printFull(As)

4×5 Array{Union{AbstractString, Number},2}:
 ""    "a"    "b"    "c"    "d"   
 "a"   "a-a"  ""     "a-c"  ""    
 "ab"  ""     ""     ""     "ab-d"
 "b"   ""     "b-b"  ""     ""    

In [24]:
printFull(CatValMul(As,As))

3×4 Array{Union{AbstractString, Number},2}:
 ""   "a"         "b"         "c"       
 "a"  "a-a;a-a;"  ""          "a-a;a-c;"
 "b"  ""          "b-b;b-b;"  ""        

3
Union{AbstractString, Number}["a"]
aa-a
Union{AbstractString, Number}["b"]
bb-b
Union{AbstractString, Number}["a"]
aa-a


In [26]:
printFull(As2*As2)

3×4 Array{Union{AbstractString, Number},2}:
 ""    "a"   "b"   "c"
 "a"  4     0     8   
 "b"  0     9     0   

In [13]:
CatValMul(A,A)

Assoc(Union{AbstractString, Number}[1, 2, 3], Union{AbstractString, Number}[1, 2], Union{AbstractString, Number}[1.0], 
  [1, 1]  =  121
  [3, 1]  =  363
  [2, 2]  =  484)

In [37]:
SplitStr(["abc,def", "123,456", "qwe,rty"], ",")

(SubString{String}["abc", "123", "qwe"], SubString{String}["def", "456", "rty"])

In [40]:
NumStr("a,b,c,d,")

4

In [43]:
CatStr(["a", "b"], ",", ["c", "d"])

2-element Array{String,1}:
 "a,c"
 "b,d"

In [48]:
Asv2c = val2col(As, ",")
printFull(Asv2c)

4×5 Array{Union{AbstractString, Number},2}:
 ""     "a,a-a"   "b,b-b"   "c,a-c"   "d,ab-d"
 "a"   1         0         1         0        
 "ab"  0         0         0         1        
 "b"   0         1         0         0        

In [51]:
printFull(col2type(Asv2c, ","))

4×5 Array{Union{AbstractString, Number},2}:
 ""    "a"    "b"    "c"    "d"   
 "a"   "a-a"  ""     "a-c"  ""    
 "ab"  ""     ""     ""     "ab-d"
 "b"   ""     "b-b"  ""     ""    